# Generated by Django 5.2.8 on 2025-12-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiblePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='passages',
            field=models.ManyToManyField(blank=True, related_name='journal_entries', to='journal.biblepassage'),
        ),
    ]
