# Generated by Django 5.2.8 on 2026-04-09 19:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_biblepassage_journalentry_passages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='journal_type',
            field=models.CharField(choices=[('plan', 'Reading Plan'), ('free', 'Free Form')], default='plan', max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='passage_ref',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='ReadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=5)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('start_verse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_verse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_read', models.DateField(default=datetime.date.today)),
                ('source', models.CharField(choices=[('journal', 'From journal entry'), ('manual', 'Marked manually')], default='manual', max_length=10)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_records', to='journal.journalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['book_id', 'chapter', 'start_verse'],
            },
        ),
    ]
